### ISSUE TITLE
v2.4.3 loosing app context with Flask

### ISSUE THREAD

**Issue by wolffparkinson** [cs91chris/flask_logify#3]
### Output with v2.4.2
The same configuration file when loaded with v2.4.2 works as intended
![image](https://user-images.githubusercontent.com/84867169/126065101-719ca355-8107-4d2a-a7ff-fe99bcd2d3ff.png)

### config.yaml
```yaml
version: 1
disable_existing_loggers: true

formatters:
  consoleSimple1:
    (): flask_logify.formatters.RequestFormatter
    request_id_header: X-Request-ID
    format: "[%(asctime)s] [%(levelname)s] [%(request_id)s]: %(message)s"
handlers:
  console:
      class: logging.StreamHandler
      stream: ext://sys.stdout

  consoleDevelopment:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    formatter: consoleSimple
    level: DEBUG
loggers:
  flask-development:
    handlers: [ consoleDevelopment,file,file_json]
    level: DEBUG
    propogate: yes
```

### Traceback errors with v2.4.3
```python
[2021-07-18 16:38:14,987] ERROR in logging: bad configuration file: ./logs/config.yaml
[2021-07-18 16:38:14,988] ERROR in logging: the configuration below

[2021-07-18 16:38:14,988] ERROR in logging: Unable to configure formatter 'consoleSimple1'
Traceback (most recent call last):
  File "c:\users\username\appdata\local\programs\python\python39\lib\logging\config.py", line 543, in configure
    formatters[name] = self.configure_formatter(
  File "c:\users\username\appdata\local\programs\python\python39\lib\logging\config.py", line 655, in configure_formatter
    result = self.configure_custom(config)
  File "c:\users\username\appdata\local\programs\python\python39\lib\logging\config.py", line 474, in configure_custom
    result = c(**kwargs)
  File "S:\Projects\Programming\2021\project_test\env\lib\site-packages\flask_logify\formatters.py", line 12, in __init__   
    self.app_name = flask.current_app.config['LOG_APP_NAME']
  File "S:\Projects\Programming\2021\project_test\env\lib\site-packages\werkzeug\local.py", line 422, in __get__
    obj = instance._get_current_object()
  File "S:\Projects\Programming\2021\project_test\env\lib\site-packages\werkzeug\local.py", line 544, in _get_current_object
    return self.__local()  # type: ignore
  File "S:\Projects\Programming\2021\project_test\env\lib\site-packages\flask\globals.py", line 47, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in some way. To solve
this, set up an application context with app.app_context().  See the
documentation for more information.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "S:\Projects\Programming\2021\project_test\env\lib\site-packages\flask_logify\logging.py", line 66, in init_app      
    logging.config.dictConfig(self._conf)
  File "c:\users\username\appdata\local\programs\python\python39\lib\logging\config.py", line 809, in dictConfig
    dictConfigClass(config).configure()
  File "c:\users\username\appdata\local\programs\python\python39\lib\logging\config.py", line 546, in configure
    raise ValueError('Unable to configure '
ValueError: Unable to configure formatter 'consoleSimple1'
```

**Comment by cs91chris** [comment]
Hi, your config file is malformed, check it. For the issue, yes with 2.4.3 you need an app context, like this:
```python
logging = FlaskLogging()

    with app.app_context():
        logging.init_app(app)
```

It is necessary in order to read `LOG_APP_NAME` from app config. So if you use `RequestFormatter` or `FlaskSysLogHandler` you need an app context, else you don't need it.
